name: Build and Deploy to GitHub Pages

env:
  GITHUB_USER: GGapa       # 你的 Github 账号名
  REPO_NAME: ZhiHuArchive      # 你的 Github 仓库名
  SITE_TITLE: GGapa 的知乎备份     # 你的站点名
  SITE_DESCRIPTION: GGapa 的知乎文章和回答备份目录     # 你的站点描述，用于搜索引擎

on:
  push:
    branches:
      - main
      - dev
    paths: 
      - '**.json'
      - 'render.py'
      - 'summary.py'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Python scripts
        run: |
          python render.py
          python summary.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          force_orphan: true
